int somaCubos(int n);
void imprimeNaturaisCrescente(int n);
void imprimeNaturaisDecrescente(int n);
int somaElementos(int *vetor, int n);
float mediaElementos(int *vetor, int n, int m);
int potenciaXY(int x, int y);
void imprimeString(char *string);
int retornaInvertido(int n, int *aux);
void imprimeBinario(int n);
int menorElemento(int *vetor, int n);